Web/AllegroExtended.Web/Controllers/ClassEventController.cs
namespace AllegroExtended.Web.Controllers
{
    using System;
    using System.Linq;
    using System.Web.Mvc;

    using Infrastructure.Mapping;
    using Microsoft.AspNet.Identity;
    using Services.Data;
    using ViewModels.ClassEvent;

    public class ClassEventController : BaseController
    {
        private readonly IClassEventService events;
        private readonly IUserService users;

        public ClassEventController(IClassEventService events, IUserService users)
        {
            this.events = events;
            this.users = users;
        }

        [HttpGet]
        public ActionResult All()
        {
            var currenUser = this.users.GetById(this.User.Identity.GetUserId());
            var currenUserWithPermissions = this.users.GetPermissionsById(this.User.Identity.GetUserId());
            this.ViewBag.Permissions = currenUserWithPermissions.FirstOrDefault().Group.Permissions;

            var visibleEvents = this.events.GetAll()
                                .Where(e => e.Permissions.Any(p => p.Group.Id == currenUser.GroupId))
                                .To<ClassEventViewModel>()
                                .ToList();

            return this.View(visibleEvents);
        }

        [HttpGet]
        public ActionResult Trigger(int id = 1)
        {
            // TODO: Connection to the Allegro web service here :)

            var ev = this.events.GetById(id);
            ev.LastRunOn = DateTime.Now;
            this.events.SaveChanges();

            this.TempData["Notification"] = "Event Triggered!";

            return this.Redirect("/ClassEvent/All");
        }

        [HttpGet]
        public ActionResult Edit(int id = 1)
        {
            var currenUser = this.users.GetById(this.User.Identity.GetUserId());
            var currenUserWithPermissions = this.users.GetPermissionsById(this.User.Identity.GetUserId());
            this.ViewBag.Permissions = currenUserWithPermissions.FirstOrDefault().Group.Permissions;
            this.ViewBag.Id = id;

            var visibleEvents = this.events.GetAll()
                                .Where(e => e.Permissions.Any(p => p.Group.Id == currenUser.GroupId))
                                .To<ClassEventViewModel>()
                                .ToList();

            return this.View(visibleEvents);
        }

        [HttpPost]
        public ActionResult Edit(int id, ClassEventEditViewModel model)
        {
            var ev = this.events.GetById(id);
            ev.Schedule = "Weekly";

            if (model.Mon == "on") ev.Mon = true;
            if (model.Tu == "on") ev.Tu = true;
            if (model.Wed == "on") ev.Wed = true;
            if (model.Thu == "on") ev.Thu = true;
            if (model.Fri == "on") ev.Fri = true;
            if (model.Sat == "on") ev.Sat = true;
            if (model.Sun == "on") ev.Sun = true;

            this.events.SaveChanges();

            this.TempData["Notification"] = "Event schedule changed!";

            return this.Redirect("/classevent/all");
        }

        [HttpGet]
        public ActionResult EditMonthly(int id = 1)
        {
            var currenUser = this.users.GetById(this.User.Identity.GetUserId());
            var currenUserWithPermissions = this.users.GetPermissionsById(this.User.Identity.GetUserId());
            this.ViewBag.Permissions = currenUserWithPermissions.FirstOrDefault().Group.Permissions;
            this.ViewBag.Id = id;

            var visibleEvents = this.events.GetAll()
                                .Where(e => e.Permissions.Any(p => p.Group.Id == currenUser.GroupId))
                                .To<ClassEventViewModel>()
                                .ToList();

            return this.View(visibleEvents);
        }

        [HttpPost]
        public ActionResult EditMonthly(int id, ClassEventEditViewModel model)
        {
            var ev = this.events.GetById(id);
            ev.Schedule = "Monthly";
            ev.MonthlyDate = model.MonthlyDate;
            this.events.SaveChanges();

            this.TempData["Notification"] = "Event schedule changed!";

            return this.Redirect("/classevent/all");
        }

        [HttpGet]
        public ActionResult EditOnce(int id = 1)
        {
            var currenUser = this.users.GetById(this.User.Identity.GetUserId());
            var currenUserWithPermissions = this.users.GetPermissionsById(this.User.Identity.GetUserId());
            this.ViewBag.Permissions = currenUserWithPermissions.FirstOrDefault().Group.Permissions;
            this.ViewBag.Id = id;

            var visibleEvents = this.events.GetAll()
                                .Where(e => e.Permissions.Any(p => p.Group.Id == currenUser.GroupId))
                                .To<ClassEventViewModel>()
                                .ToList();

            return this.View(visibleEvents);
        }

        [HttpPost]
        public ActionResult EditOnce(int id, ClassEventEditViewModel model)
        {
            var ev = this.events.GetById(id);
            ev.Schedule = "Once";
            ev.Date = model.Date;
            this.events.SaveChanges();

            this.TempData["Notification"] = "Event schedule changed!";

            return this.Redirect("/classevent/all");
        }
    }
}

Web/AllegroExtended.Web/Views/Shared/_Layout.cshtml
@using AllegroExtended.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - AllegroExtended</title>
    @Styles.Render("~/Content/css")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Allegro Scheduler", "All", "ClassEvent", new { area = string.Empty }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>
                    @if (this.User.IsInRole(GlobalConstants.AdministratorRoleName))
                    {
                        <li>@Html.ActionLink("Administartion", "Index", "HomePanel", new { area = "Administration" }, null)</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div id="content-body" class="container body-content">
        @RenderBody()
    </div>
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year - AllegroExtended</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>